name: Anti Bruteforce
on:
  push:
env:
  GO111MODULE: "on"
jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v2
      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -race -timeout=1m ./...
      - name: Build
        run: make build
